### PR TITLE
Implement driver.ConnBeginTx

### PR DESCRIPTION
**Pull request by m12i**
This change implements `driver.ConnBeginTx` interface so that sqlhooks can be used when a non default isolation level is used.

---
This change is [Reviewable](https://reviewable.io/reviews/gchaincl/sqlhooks/24)

### CODE REVIEW

**Comment by gchaincl** [comment]
Is there any way to test this?

**Comment by m12i** [comment]
Just bringing this PR to your attention again

**Comment by gchaincl** [comment]
Thanks for addressing this and sorry for not getting back, I'll review it
this week.

**Comment by keegancsmith** [comment]
aah I see now from the godoc of `BeginTx`:

> If a non-default isolation level is used that the driver doesn't support, an error will be returned.

Ok so this retains the behaviour. I would actually duplicate what sql/db returns in the case the interface is not implemented: https://sourcegraph.com/github.com/golang/go@go1.12/-/blob/src/database/sql/ctxutil.go#L110-120

**Comment by keegancsmith** [comment]
> Since there is no way to support both, I think sqlhooks should stick with the majority (and most popular) drivers. Does that make sense?

There is a way, you do type checks against the driver to find out, if it does you return a driver which does support BeginCtx. We do that in other parts of sqlhooks. However, given what you said I agree. Rather make sqlhooks just support the majority. Not sure what @gchaincl thinks.

**Comment by keegancsmith** [comment]
See the Open function.

**Comment by gchaincl** [comment]
I'm not sure about what's the best choice here, although dropping support for the drivers that don't implement `BeginTx` sounds reasonable, it's not ideal since we (or at least I) don't know for sure what the affected drivers are. I like the idea of duplicating what https://sourcegraph.com/github.com/golang/go@go1.12/-/blob/src/database/sql/ctxutil.go#L110-120 is doing, even if the code might change, the impact shouldn't huge.

**Comment by gchaincl** [comment]
any progress on this @m12i ?

**Pull request closed without merging**
